module.exports = {
  projects: [
    '<rootDir>/apps/react-html5up-templates/hyperspace/react-html5up-hyperspace',
    '<rootDir>/libs/react-html5up',
    '<rootDir>/libs/react-html5up/src/components',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/button',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/icon',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/link',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/heading',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/quote',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/code',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/text',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/list',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/table',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/input',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/radio',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/navbar',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/footer',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/sidenav',
    '<rootDir>/libs/react-html5up/src/components/src/lib/hyperspace/src/lib/intro',
    '<rootDir>/libs/react-html5up/src/utilities',
    '<rootDir>/libs/react-html5up/src/utilities/src/lib/style-reset',
  ],
};
