name: 'Packages Split'

on:
  push:
    branches:
      - workspace-desktop
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - react-uwp_local_path: 'react-uwp'
            next10_local_path: 'next10'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - name: 'Split react-uwp repository'
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          package-directory: 'libs/${{ matrix.package.react-uwp_local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.react-uwp_local_path }}'
          branch: 'workspace-desktop'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'
      - name: 'Split next10 repository'
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          package-directory: 'apps/${{ matrix.package.next10_local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.next10_local_path }}'
          branch: 'workspace-desktop'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'

      # with tag
      - name: 'Split react-uwp repository'
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: 'libs/${{ matrix.package.react-uwp_local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.react-uwp_local_path }}'
          branch: 'workspace-desktop'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'
      - name: 'Split next10 repository'
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: 'symplify/monorepo-split-github-action@2.0'
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: 'apps/${{ matrix.package.next10_local_path }}'
          split-repository-organization: 'morteza-jamali'
          split-repository-name: '${{ matrix.package.next10_local_path }}'
          branch: 'workspace-desktop'
          user-name: 'morteza-jamali'
          user-email: 'mortezajamali4241@gmail.com'
